[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"
  # Don't externalize redis since you're using @upstash/redis (HTTP-based, not native)
  external_node_modules = ["xrpl"]
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"