# Netlify Configuration for the Next.js Backend
[build]
  command = "npm run build"
  publish = ".next"

# Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# CORS headers for API routes - ALLOW ALL ORIGINS
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"